trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  Runtime: 'linux-x64'

steps:
  - task: UseDotNet@2
    inputs:
      version: '8.x'
  - task: DotNetCoreCLI@2
    name: Restore
    inputs:
      command: 'restore'
      projects: 'src/**/Bot.fsproj'
      arguments: '-r $(Runtime)'
  - task: DotNetCoreCLI@2
    name: Build
    inputs:
      command: 'build'
      configuration: 'Release'
      projects: 'src/**/Bot.fsproj'
      arguments: '-r $(Runtime) -c Release'
      publishWebProjects: false
  - task: DotNetCoreCLI@2
    name: Publish
    inputs:
      command: 'publish'
      configuration: 'Release'
      projects: 'src/**/Bot.fsproj'
      arguments: '-r $(Runtime) -c Release -o $(Build.ArtifactStagingDirectory)'
      publishWebProjects: false
  - task: PublishBuildArtifacts@1
    name: Pack
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'