version: '3.0'

services:
  webm-to-mp4-telegram-bot-dev:
    container_name: webm-to-mp4-telegram-bot-dev
    image: webm-to-mp4-telegram-bot:dev
    restart: always
    build:
      context: .
      dockerfile: ./Bot/Dockerfile
    depends_on:
      - telegram-bot-api
    environment:
      Telegram:Token:
      Services:CleanerQueueUrl:
      Services:ConverterQueueUrl:
      Services:DownloaderQueueUrl:
      Services:UploaderQueueUrl:
      Services:Delay: 00:01:00
      ApplicationInsights:InstrumentationKey:
      FFMpeg:Path: /usr/bin/ffmpeg
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
  telegram-bot-api:
    container_name: telegram-bot-api
    image: aiogram/telegram-bot-api:latest
    restart: always
    ports:
      - "65500:8081"
    volumes:
      - /telegram-bot-api-data:/var/lib/telegram-bot-api
    environment:
      TELEGRAM_API_ID:
      TELEGRAM_API_HASH:
      TELEGRAM_LOCAL: 'true'