version: '3.0'

services:
  webm-to-mp4-telegram-bot-dev:
    container_name: webm-to-mp4-telegram-bot-dev
    image: webm-to-mp4-telegram-bot:dev
    restart: always
    build:
      context: ./src/
      dockerfile: ./Bot/Dockerfile
    depends_on:
      - nginx-telegram-bot-api
    environment:
      Telegram:Token:
      Telegram:ApiUrl: "http://nginx-telegram-bot-api"
      Services:CleanerQueueUrl:
      Services:ConverterQueueUrl:
      Services:DownloaderQueueUrl:
      Services:UploaderQueueUrl:
      Services:Delay: 00:01:00
      ApplicationInsights:InstrumentationKey:
      FFMpeg:Path: /usr/bin/ffmpeg
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
  nginx-telegram-bot-api:
    image: nginx:alpine
    restart: always
    depends_on:
      - telegram-bot-api
    volumes:
      - /telegram-bot-api-data:/var/lib/telegram-bot-api
      - ./config/nginx:/etc/nginx/conf.d/
    ports:
      - "65500:80"
  telegram-bot-api:
    container_name: telegram-bot-api
    image: aiogram/telegram-bot-api:latest
    restart: always
    volumes:
      - /telegram-bot-api-data:/var/lib/telegram-bot-api
    environment:
      TELEGRAM_API_ID:
      TELEGRAM_API_HASH:
      TELEGRAM_LOCAL: 'true'